'use strict';

let startBtn = document.getElementById('start'),
    budVal = document.getElementsByClassName('budget-value'),
    dayBudVal = document.getElementsByClassName('daybudget-value'),
    levelVal = document.getElementsByClassName('level-value'),
    expVal = document.getElementsByClassName('expenses-value'),
    optExpVal = document.getElementsByClassName('optionalexpenses-value'),
    incomeVal = document.getElementsByClassName('income-value'),
    monthsavingsVal = document.getElementsByClassName('monthsavings-value'),
    yearsavingsVal = document.getElementsByClassName('yearsavings-value'),
    expItems = document.getElementsByClassName('expenses-item'),
    data = document.getElementsByClassName("data"),
    optExpbtn = data.getElementsByTagName("button")[0],
    countBudbtn = data.getElementsByTagName("button")[1],
    optExpensesItems = document.querySelectorAll(".optionalexpenses-item"),
    expensesItemBtn = document.querySelector('.expenses-item-btn'),
    optExpensesBtn = document.querySelector('.optionalexpenses-btn'),
    countBudBtn = document.querySelector('.count-budget-btn'),
    chooseIncome = document.querySelector('.choose-income'),
    savings = document.querySelector('.savings'),
    chooseSum = document.querySelector('.choose-sum'),
    choosePersent = document.querySelector('.choose-persent'),
    yearInp = document.getElementsByClassName('year-value'),
    monthInp = document.getElementsByClassName('month-value'),
    dayInp = document.getElementsByClassName('day-value');